/*
 *
 * Plans constants
 *
 */

export const DEFAULT_ACTION = 'app/Plans/DEFAULT_ACTION';
export const REQUEST_PLANS = 'app/Plans/REQUEST_PLANS';
export const REQUEST_PLANS_SUCCESS = 'app/Plans/REQUEST_PLANS_SUCCESS';
export const REQUEST_PLANS_ERROR = 'app/Plans/REQUEST_PLANS_ERROR';

export const REQUEST_TABLE_DATA = 'app/Plans/REQUEST_TABLE_DATA';
export const REQUEST_TABLE_DATA_SUCCESS ='app/Plans/REQUEST_TABLE_DATA_SUCCESS';
export const REQUEST_TABLE_DATA_ERROR = 'app/Plans/REQUEST_TABLE_DATA_ERROR';

export const REQUEST_PROJECTS_DATA = 'app/Plans/REQUEST_PROJECTS_DATA';
export const REQUEST_PROJECTS_DATA_SUCCESS = 'app/Plans/REQUEST_PROJECTS_DATA_SUCCESS';
export const REQUEST_PROJECTS_DATA_ERROR = 'app/Plans/REQUEST_PROJECTS_DATA_ERROR';
